spring:
  application:
    name: auth-service
  config:
    import: optional:classpath:application-private.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5001/tad_db?currentSchema=auth&ApplicationName=tad-auth
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

server:
  port: 9000
  servlet:
    context-path: /auth

app:
  oauth2:
    google:
      client-id: ${GOOGLE_CLIENT_ID:}
  jwt:
    issuer: ${JWT_ISSUER:tad-auth}
    secret-base64: ${JWT_SECRET_BASE64:}
    access-minutes: ${JWT_ACCESS_MINUTES:15}
    refresh-days: ${JWT_REFRESH_DAYS:14}

logging:
  level:
    root: INFO